### ISSUE TITLE
Looking for dataset

### ISSUE THREAD

**Issue by AlfredChung** [Harvard-Ophthalmology-AI-Lab/FairCLIP#1]
Hi ,friends. The dataset download link is no longer valid, please update the link, thank you very much!

**Comment by luoyan407** [comment]
Thanks for reaching out. The dataset download link is valid, but it is based on request. Please click the 'request access' button when redirecting to Google Drive. We will grant you access within one to two days.

**Comment by AlfredChung** [comment]
Thank you for your reply. I have submitted the request and hope you can authorize me to use it. Best regards！
